In [57]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from scipy.stats import multivariate_normal

In [25]:
data_crab = np.loadtxt("CrabDatasetforTrain.txt",dtype = "double")
print(data_crab)

[[15.  11.9 32.5 ...  1.   0.   1. ]
 [18.2 13.7 38.8 ...  1.   0.   0. ]
 [18.9 16.7 36.3 ...  0.   1.   0. ]
 ...
 [12.6 12.2 26.1 ...  0.   1.   1. ]
 [19.7 16.7 39.9 ...  0.   1.   0. ]
 [ 9.6  7.9 20.1 ...  1.   0.   1. ]]


In [24]:
# split data
data_c_label = data_crab[:,-1]
# print(data_c_label)
# print(data_c_train.shape)
data_c_features = data_crab[:,0:-1]
# print(data_c_features)

In [33]:
kf = KFold(n_splits=5) # Define the split - into 5 folds

In [60]:
for train_index, test_index in kf.split(data_c_features):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = data_c_features[train_index], data_c_features[test_index]
    y_train, y_test = data_c_label[train_index], data_c_label[test_index]
    
    
    # likelihood function is multivariate_gaussian.
    p_L = np.random.multivariate_normal(mean1,cov1,c='r')
    # since is two-class classification, we can get mean from log likelihhod estimation
    
    # this is  the prior of class 1
    p_prior_1 = data_c_label[ data_c_label==1.0 ].size/data_crab.shape[0]
    
    # this is the prior of class 0
    p_prior_0 = data_c_label[ data_c_label==0.0 ].size/data_crab.shape[0]
    
    # num of data points?
#     data_crab.shape[0]
    mean1 = np.mean(data_crab[data_c_label == 1.0],axis=0)[:,0:-1]
    mean0 = np.mean(data_crab[data_c_label == 0.0],axis=0)[:,0:-1]
    
    cov1 = np.cov(data_crab[data_c_label==1.0][;,0:-1])
    cov0 = np.cov(data_crab[data_c_label==0.0][;,0:-1])
    
    p_L_1 = multivariate_normal.pdf(data_c_features,mean = mean1,cov=cov1)

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    y_train, y_test = data_c_label[train_index], data_c_label[test_index]

TRAIN: [ 27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44
  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62
  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80
  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116
 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133] TEST: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


NameError: name 'cov1' is not defined

In [44]:
p_prior_1 = data_c_label[ data_c_label==1.0 ].size
print(p_prior_1)

68


In [43]:
data_crab.shape[0]

134

In [64]:
data_crab[data_c_label == 1.0][:,0:-1]


array([[15. , 11.9, 32.5, 37.2, 13.6,  1. ,  0. ],
       [12.9, 11. , 26.8, 30.9, 11.4,  1. ,  0. ],
       [15.8, 15. , 34.5, 40.3, 15.3,  0. ,  1. ],
       [12.6, 10. , 27.7, 31.7, 11.4,  1. ,  0. ],
       [12.8, 10.9, 27.4, 31.5, 11. ,  1. ,  0. ],
       [15.6, 13.9, 32.8, 37.9, 13.4,  0. ,  1. ],
       [12. , 10.7, 24.6, 28.9, 10.5,  0. ,  1. ],
       [19.8, 14.2, 43.2, 49.7, 18.6,  1. ,  0. ],
       [ 8.8,  7.7, 18.1, 20.8,  7.4,  1. ,  0. ],
       [10.4,  9.7, 21.7, 25.4,  8.3,  0. ,  1. ],
       [17.7, 13.6, 38.7, 44.5, 16. ,  1. ,  0. ],
       [16.2, 15.2, 34.5, 40.1, 13.9,  0. ,  1. ],
       [11.5, 11. , 24.7, 29.2, 10.1,  0. ,  1. ],
       [16.7, 16.1, 36.6, 41.9, 15.4,  0. ,  1. ],
       [11.6, 11.4, 23.7, 27.7, 10. ,  0. ,  1. ],
       [13.1, 10.9, 28.3, 32.4, 11.2,  1. ,  0. ],
       [11.8,  9.6, 24.2, 27.8,  9.7,  1. ,  0. ],
       [11.6, 11. , 24.6, 28.5, 10.4,  0. ,  1. ],
       [19.3, 13.5, 41.6, 47.4, 17.8,  1. ,  0. ],
       [16.4, 13. , 35.7, 41.8,

In [51]:
# mean1 of all features
mean1 = np.mean(data_crab[data_c_label == 1.0],axis=0)
print(mean1)

[13.88823529 11.86029412 29.61617647 34.18529412 12.36323529  0.47058824
  0.52941176  1.        ]


In [53]:
var1 = np.var(data_crab[data_c_label == 1.0],axis=0)
var2 = np.var(data_crab[data_c_label == 0.0],axis=0)
var1

array([ 8.40250865,  4.88739403, 43.93753244, 56.16507785,  8.50173659,
        0.24913495,  0.24913495,  0.        ])

In [59]:
np.cov(data_c_features)

array([[204.36142857, 238.305     , 226.29095238, ..., 167.64880952,
        241.78619048, 125.44809524],
       [238.305     , 278.40333333, 263.80666667, ..., 195.12333333,
        282.52166667, 146.18666667],
       [226.29095238, 263.80666667, 252.86619048, ..., 187.0047619 ,
        269.31190476, 139.09761905],
       ...,
       [167.64880952, 195.12333333, 187.0047619 , ..., 138.77571429,
        199.02095238, 103.01714286],
       [241.78619048, 282.52166667, 269.31190476, ..., 199.02095238,
        288.01238095, 148.40452381],
       [125.44809524, 146.18666667, 139.09761905, ..., 103.01714286,
        148.40452381,  77.07142857]])

In [75]:
cov1 = np.cov(data_crab[data_c_label==1.0][:,0:-1])
cov1.shape

(68, 68)

In [77]:
data_crab[data_c_label==1.0][:,0:-1].shape

(68, 7)

In [74]:
p_L_1 = multivariate_normal.pdf(data_c_features,mean = mean1,cov=cov1)

ValueError: Dimension mismatch: array 'cov' is of shape (68, 68), but 'mean' is a vector of length 8.